# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * EdgeX Foundry, Fuji, version 1.1.0
#  * added: Jun 30, 2019
#  * edit: Feb 10, 2020 by hgg 1778006949@qq.com
#  *******************************************************************************/

# NOTE:  this Docker Compose file does not contain the security services - namely the API Gateway and Secret Store

version: '3.4'

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  edgex_registry: consul://edgex-core-consul:8500
  Clients_CoreData_Host: edgex-core-data
  Clients_Logging_Host: edgex-support-logging
  Logging_EnableRemote: "true"

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:
  rules-templates:
  rules-uploads:
  db-devicevirtual:
  images:

services:
  volume:
    image: guqiaochina/docker-edgex-volume:1.1.1
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - rules-templates:/edgex/edgex-support-rulesengine/templates
      - rules-uploads:/edgex/edgex-support-rulesengine/rules

  consul:
    image: consul:1.3.1
    ports:
      - "8400:8400"
      - "8500:8500"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  config-seed:
    image: guqiaochina/docker-core-config-seed-go:1.1.1
    command: ["--profile=docker", "--cmd=/edgex/cmd-redis","--overwrite=true"]
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
            - edgex-core-config-seed
    environment:
      <<: *common-variables            
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - consul

  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
    container_name: edgex-redis
    hostname: edgex-redis
    networks:
      - edgex-network
    volumes:
      - db-data:/data
    depends_on:
      - volume

  logging:
    image: guqiaochina/docker-support-logging-go:1.1.0
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    environment: 
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - consul
      - redis

  system:
    image: guqiaochina/docker-sys-mgmt-agent-go:1.1.0
    ports:
      - "48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logging

  notifications:
    image: guqiaochina/docker-support-notifications-go:1.1.0
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging
#      - redis

  metadata:
    image: guqiaochina/docker-core-metadata-go:1.1.0
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  data:
    image: guqiaochina/docker-core-data-go:1.1.0
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  command:
    image: guqiaochina/docker-core-command-go:1.1.0
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata
      - data

  scheduler:
    image: guqiaochina/docker-support-scheduler-go:1.1.0
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - command

  app-service-rules:
    image: guqiaochina/docker-app-service-configurable:1.0.0
    ports:
      - "48100:48100"
    container_name: edgex-app-service-configurable-rules
    hostname: edgex-app-service-configurable-rules
    networks:
      edgex-network:
        aliases:
          - edgex-app-service-configurable-rules
    environment:
      <<: *common-variables
      edgex_service: http://edgex-app-service-configurable-rules:48100
      edgex_profile: rules-engine
      Service_Host: edgex-app-service-configurable-rules
      MessageBus_SubscribeHost_Host: edgex-core-data
    depends_on:
      - command

  rulesengine:
    image: guqiaochina/support-rulesengine:1.1.0
    ports:
      - "48075:48075"
    container_name: support-rulesengine
    hostname: support-rulesengine
    networks:
      edgex-network:
        aliases:
          - edgex-support-rulesengine
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - rules-templates:/edgex/edgex-support-rulesengine/templates
      - rules-uploads:/edgex/edgex-support-rulesengine/rules
    depends_on:
      - app-service-rules


  edgex-mosquitto:
    image: guqiaochina/docker_eclipse-mosquitto:lastest
    ports:
      - "1883:1883"
    container_name: edgex-mosquitto
    hostname: edgex-mosquitto
    networks:
      - edgex-network

  export-client:
    image: guqiaochina/docker-export-client-go:1.1.0
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - command
  #
  export-distro:
    image: guqiaochina/docker-export-distro-go:1.1.0
    ports:
      - "48070:48070"
      - "5567:5567"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client
    environment:
      <<: *common-variables
      EXPORT_DISTRO_CLIENT_HOST: export-client
      EXPORT_DISTRO_DATA_HOST: edgex-core-data
      EXPORT_DISTRO_CONSUL_HOST: edgex-config-seed
      EXPORT_DISTRO_MQTTS_CERT_FILE: none
      EXPORT_DISTRO_MQTTS_KEY_FILE: none

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: guqiaochina/docker-device-virtual-go:1.1.1
    ports:
      - "49990:49990"
    container_name: device-virtual
    hostname: device-virtual
    networks:
      edgex-network:
        aliases:
          - edgex-device-virtual
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - db-devicevirtual:/db # Mount ql database directory is optional
    depends_on:
      - export-distro

  device-simple:
    image: guqiaochina/docker-device-sdk-simple:1.1.1
    ports:
      - "49992:49992"
    container_name: edgex-device-simple
    hostname: edgex-device-simple
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-distro

  # device-random:
  #   image: edgexfoundry/docker-device-random-go:1.1.0
  #   ports:
  #     - "49988:49988"
  #   container_name: edgex-device-random
  #   hostname: edgex-device-random
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  device-mqtt:
    image: guqiaochina/docker-device-mqtt-go:1.1.0
    ports:
      - "49982:49982"
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-distro
      - edgex-mosquitto

  device-modbus:
     image: guqiaochina/docker-device-modbus-go:1.1.1
     ports:
       - "49991:49991"
     container_name: edgex-device-modbus
     hostname: edgex-device-modbus
     networks:
       - edgex-network
     volumes:
       - log-data:/edgex/logs
       - consul-config:/consul/config
       - consul-data:/consul/data
     depends_on:
       - command
       - export-distro

  device-camera:
    image: guqiaochina/device-camera-go:1.0.0
    ports:
      - "49985:49985"
    container_name: edgex-device-camera
    hostname: edgex-device-camera
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - command
      - export-distro
  # device-snmp:
  #   image: edgexfoundry/docker-device-snmp-go:1.1.0
  #   ports:
  #     - "49993:49993"
  #   container_name: edgex-device-snmp
  #   hostname: edgex-device-snmp
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command

#################################################################
# UIs
#################################################################
  ui:
    image: guqiaochina/docker-edgex-ui-go:1.1.1
    ports:
      - "4000:4000"
    container_name: edgex-ui-go
    hostname: edgex-ui-go
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-distro
      

#################################################################
# Tooling
#################################################################

  portainer:
    image:  portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    depends_on:
      - ui

networks:
  edgex-network:
    driver: "bridge"

